### ISSUE TITLE
Multi mode: none option not functional

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1038]
# Bug

## Expected Behavior

GIVEN the map is in multi mode

WHEN clicking on the used maps and then on the `NONE` option

THEN ??? it's unclear what should happen without a map. Let's define this in a discussion in this issue

## Actual Behavior

Nothing happens. Clicking out of the option and back into it shows the last setting active instead of `NONE`.

## Screenshots

![image](https://user-images.githubusercontent.com/8822573/86520750-42735980-be48-11ea-8216-a891d4f20d05.png)

## Specifications

- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.49.1
- OS: Ubuntu 20.04
- Browser: Chromium

**Comment by NearW** [comment]
None is actually working as we intended it to be. CodeCharta is only working with a file and a map loaded based on that. The state where no file is given or no map is selected is invalid. Clicking on `NONE` would result in a state where no map is selected. That's why we don't change the state at all when clicking it. But from there on, you can select individual maps and update the state again. This is pretty handy when you have 10 maps open and want to deselect all but one. You simply click on `NONE` and then select the desired one.

When you click `NONE` and then close the chooser again, you won't end up in an invalid state either. We just go back to how it was before. :)

**Comment by BridgeAR** [comment]
I already expected something like that. I understand the reasoning but it does not seem like an intuitive behavior since the other two options work very different.

Let's try to rethink the UI for this case a bit to hopefully find a better solution.

**Comment by NearW** [comment]
When checking a file to be selected a rebuilding of the map is triggered. Maybe it makes sense to add an `Apply`-button to it. In that case we can select like 5 maps and then press apply in order to trigger a rebuilding once.
There might be the case where we select a huge map and after selecting each map it takes 5s to rebuild or something. That would be bad user experience, if the user had to select like 5 maps.

Also when using an apply button, `ALL` and `INVERT` would have the same behaviour as `NONE`, which is to not trigger a rebuilding of the map.

**Comment by BridgeAR** [comment]
Yes, adding an apply button does seem useful here. We should definitely do that! In case no map is selected, the `Apply` button would be grey and not clickable.

We could special handle the case that the user has exactly two maps: in that case we do not have to provide `NONE` as option and apply the changes immediately as it's done right now. Deselecting the last map should in that case not be possible and that should be indicated by showing a grey non-clickable button. I am fine to keep it simple though and just use apply for now.

**Comment by ChristianHuehn** [comment]
Multi mode doesnt exist anymore. A part of the discussion will be implemented in https://github.com/MaibornWolff/codecharta/issues/3637
