### ISSUE TITLE
Set Metrics via Url Parameters

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#1091]
# Feature request

## Description

I want to be able to share a link of my map to someone and thereby say: "look at this map with these metrics" 

Currently I can send someone a link and need to tell him to "set Size metric to Rloc", "set height metric to x".

## Acceptance criteria

Suggested solution: 

- when I open a CodeCharta url in my browser, the metric values in the url should be used in the visualization, if none are provided, the default values should be used
- whenever I copy the CodeCharta Url, the url should have the current values
- unknown url parameter values don't break CC, likewise parameter values with a wrong type (text provided, number needed)
- idea: whenever a metric changes, please put the current value into the url
- idea: whenever I apply a scenario, the current values are in the url
- Optional: when I open CC for the first time, the default values that are selected automatically, should be added to the url

## Assumptions & Exclusions

- The parameters do not have to be version-independent, a link from v1.45 does not have to work in v1.46 and vice-versa. It would be nice though :)

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by NearW** [comment]
@Richargh The use case here would be that Alice and Bob have the same cc.json on your computer. In that case, Alice would have to supply the path to the file in the URL parameters as well. Alice's path is not compatible with the path of Bob though.

We currently think about exporting a config file that can be loaded with the cc.json to apply a certain state (such as metrics)

**Comment by Richargh** [comment]
> The use case here would be that Alice and Bob have the same cc.json on your computer.

@NearW that's a way too unlikely usecase. 

I meant the situation where you host your own CodeCharta Instance (using the docker image f.ex.) and want to share a url to tell them to: "look at this map with these metrics". 

This scenario is applicable for the CodeCharta project which self-hosts or another project like [this one](https://github.com/cstanger/openwhisk-visualizer) that also has an online demo.

**Comment by NearW** [comment]
@Richargh Thanks for clarifying.

When Alice is hosting the webserver, Alice needs to provide the cc.jsons in a folder, that can be accessed by the web application. Running the application in a docker container makes that quite difficult, since the containers are isolated. Therefore the cc.json files need to be added to the container before.

But since setting up the server is not part of this issue, the implementation here is straight forward.
I think we should add some documentation afterwards though. :)

**Comment by BridgeAR** [comment]
I thought about this again and the config feature that is planned would be more powerful than this one, since it's possible to let the other user experience exactly the same as the current user and not only a part of it. We could also add a convenient copy mechanism to share configs as strings and we could add a "share" mechanism that serializes the config as json and adds it to a single query parameter that could be shared for these cases. The configs should be small enough that this should be fine. The sharing functionality should also only be available for default maps.

**Comment by BridgeAR** [comment]
While I personally like the idea of implementing this, it's not on the roadmap anytime soon. It just does not seem like a frequent enough use case to share the configuration with someone else like that. I am therefore going to close the issue.
