### ISSUE TITLE
Prevent mouseflickering when clicking a building

### ISSUE THREAD

**Issue by JaiJoPa** [MaibornWolff/codecharta#1170]
# Feature request

## Description

When a building is clicked, then the mouse quickly changes to the drag icon. 
It would be nice, if we could prevent that it changes the mouse icon when a building is being clicked. 

## Acceptance criteria
- selecting or opening the nodeContextMenu to a building does not change the cursor icon
- when the map is rotated or moved then the cursors should change to the specific cursor icon during the process

## Assumptions & Exclusions

An idea would be to add a threshhold before showing the drag(left-clicked) or the move (left-clicked) icon

**Comment by BridgeAR** [comment]
I just had tested this and ideally, the cursor just checks for being above the map, not about being above a building, since it's also possible to click on folders and the map consistent to 100% of buildings and folders. Thus, there's no area where the cursor should not be changed.

Therefore it's also best to just use a single on hover event (from the most outer map dom element).

After looking closer, it also seems that cursor movements trigger further events while the mouse button is hold down. That is not ideal, since holding down the mouse is already a specific state and there should not be another state change while being in that state.
