### ISSUE TITLE
File parameter in URL should accept more than one file

### ISSUE THREAD

**Issue by xWorkerBeex** [MaibornWolff/codecharta#136]
## Description

It would be really handy to be able to pass more than one file via the file parameter of the URL. 

We currently use CC to visualize our software with every build of our pipeline and it would be great if we could pass the current json file and the file of the last build to be able to visualize the deltas between the two versions

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

* [x] **All** requirements mentioned in the issue are implemented
* [x] Does match the Code of Conduct and the Contribution file 
* [x] Task has its own **GitHub issue** (something it is solving)
  * [x] Issue number is **included in the commit messages** for traceability
* [x] **Update the README.md** with any changes/additions made
* [x] **Update the CHANGELOG.md** with any changes/additions made
* [x] **Enough test coverage to ensure that uncovered changes do not break functionality**
* [x] **All tests pass**    
* [x] **Descriptive pull request text**, answering:
  + What problem/issue are you fixing?
  + What does this PR implement and how? 
* [x] **Assign your PR to someone** for a code review
  + This person _will be contacted **first**_ if a bug is introduced into `master`
* [x] **Manual testing** did not fail

**Comment by FernandoES** [comment]
I think I misunderstood what you mean, I clicked in "URL PARAMETERS" and get no file parameter on that, only the followings:
?neutralColorRange.from=20
&neutralColorRange.to=40
&neutralColorRange.flipped=false
&areaMetric=Average Block Depth
&heightMetric=Average Complexity*
&colorMetric=Average Statements per Method
&deltas=false
&amountOfTopLabels=1
&scaling.x=1
&scaling.y=1
&scaling.z=1
&camera.x=7606.637893916231
&camera.y=7606.637893916233
&camera.z=7606.637893916233
&margin=15
&operation=NOTHING
&deltaColorFlipped=false
&showDependencies=false
&maximizeDetailPanel=false
&invertHeight=false
&dynamicMargin=true

**Comment by alschmut** [comment]
@FernandoES The "URL PARAMETERS" only shows the settings as said:
_"You can copy these parameters and append them as URL parameters to your CodeCharta URL in order to apply the current settings. Ctrl/Cmd + C to copy selection."_

Current example url with a possible amount of only one file loaded:
https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json

### What this issue is solving
Wanted url to accept multiple parameters:
https://maibornwolff.github.io/codecharta/visualization/app/index.html?file[]=one.cc.json&file[]=two.cc.json&file[]=three.cc.json

This will work for a single file as well:
https://maibornwolff.github.io/codecharta/visualization/app/index.html?file[]=codecharta.cc.json

Angular should get the parameters as an array then:
```
"file[]": [
    "one.cc.json",
    "two.cc.json",
    "three.cc.json"
  ]
```
Check out [stackoverflow](https://stackoverflow.com/questions/19957858/send-array-via-get-request-with-angularjs-http-service)

**Comment by mrpatpat** [comment]
We propably need to modify [this method](https://github.com/MaibornWolff/codecharta/blob/master/visualization/app/codeCharta/codeCharta.component.ts#L83) to accept multiple maps and call it from a map which iterates over the file array described by @alschmut
