### ISSUE TITLE
Label on Code Coverage shows infinite instead of 100

### ISSUE THREAD

**Issue by MarkSandy** [MaibornWolff/codecharta#1520]
# Max value of line_coverage shows as 'infinite' instead of '100'

## Legend should show e.g. >67 to 100
Select line_coverage as one of the dimensions of the charta charta

## Actual Behavior
Legen shows 'infinite' instead of 100

## Screenshots
![Legend](https://user-images.githubusercontent.com/37777241/100452565-ac232700-30b9-11eb-8fad-0ecb6e8fab73.png)

## Steps to Reproduce the Problem
See above

**Comment by ce-bo** [comment]
Thank you for your suggestion @MarkSandy

**Comment by BridgeAR** [comment]
To extend this issue: it does not only apply to `line_coverage but any metric that is in percentage and we should also update our label description in delta mode to include the word "delta" and fix the minus sign (use `&#8722;` = `−`)

![image](https://user-images.githubusercontent.com/8822573/100617029-32d63f00-331a-11eb-8607-ef86616e0da3.png)
![image](https://user-images.githubusercontent.com/8822573/100617911-682f5c80-331b-11eb-802b-96551c559155.png)

We might also think about using the effective maximum as upper range end instead of `Infinite` as in

![image](https://user-images.githubusercontent.com/8822573/100617457-d1fb3680-331a-11eb-826d-d5d1cbcc5660.png)

Otherwise we'll have to either change our parsers to include the range for coverage and other applicable metrics or we'd have to guess the range for metrics. If we guess, let's check for maximum values below 100 that contain the word "coverage". If we change the parser, let's also include the default direction of the range. The coverage case should for example be inverted by default. "high" numbers are "positive" (green) and low numbers are bad.

![image](https://user-images.githubusercontent.com/8822573/100618976-cd378200-331c-11eb-94c1-b9982aec8b2a.png)
![image](https://user-images.githubusercontent.com/8822573/100619038-e0e2e880-331c-11eb-86db-0874dbee0d67.png)
