### ISSUE TITLE
Edge metric is only shown if there are activated edges

### ISSUE THREAD

**Issue by Gaugi28** [MaibornWolff/codecharta#1542]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As user, I want that the metric `Edges` disappears if there are no activated edges so that I can't get confused about the meaning of the metric `Edges`.

## Acceptance criteria
- if there are no activated edges the metric `Edges` is hidden

**Comment by RomanenkoVladimir** [comment]
We show a tooltip and the metric appears grey.
I guess the idea was that the interface remains largely unchanged so that the user has a fast recognition factor as well as not being confused by disappering features.
The current implementation provides a feedback that the metric isn't just gone, it is disabled for the current map, with the tooltip that you need to generate edges in analysis.
What do you think if you few it under this aspect?

**Comment by Gaugi28** [comment]
Yes, I know, but for me, as user who don't know, where I can generate edges in analysis, it's difficult to understand the tooltip. I discussed it yesterday with @BridgeAR. The result was: either the tooltip tells me how to generate the edges in analysis, or the metric is hidden from the beginning.
