### ISSUE TITLE
Automatic margin to better visualize package structure.

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#164]
## Description

Margin probably needs to be automatic. 

If the area metric is RLoC and the complete tree map has 1.000.000 RLoC the margin needs to be bigger than if the complete tree map has 1.000 RLoC.

For an area of 100 RLoC the margin 20 seems to be good. For an area of 1.000 RLoC the margin of 15 seems to be good. For an area of 1.000.000 RLoC the margin of 10 might be good. This needs to be evaluated while working on this issue. 

## Definition of Done

A task/pull request will not be considered to be complete until all these items can be checked off.

* [ ] **All** requirements mentioned in the issue are implemented
* [ ] Does match the Code of Conduct and the Contribution file 
* [ ] Task has its own **GitHub issue** (something it is solving)
  * [ ] Issue number is **included in the commit messages** for traceability
* [ ] **Update the README.md** with any changes/additions made
* [ ] **Update the CHANGELOG.md** with any changes/additions made
* [ ] **Enough test coverage to ensure that uncovered changes do not break functionality**
* [ ] **All tests pass**    
* [ ] **Descriptive pull request text**, answering:
  + What problem/issue are you fixing?
  + What does this PR implement and how? 
* [ ] **Assign your PR to someone** for a code review
  + This person _will be contacted **first**_ if a bug is introduced into `master`
* [ ] **Manual testing** did not fail

**Comment by FernandoES** [comment]
In order to generalize I suggest (and implemented) to make the margin depending on the areaMetric.

The criteria used is margin = log2(areaMetric), but this is still opened to suggestions and debate.

When the metric used for area is changed the margin is also changed.

There is a failure since the size to map fitting is done before the ultimate margin calculation, so the map is wrong fitted in screen
