### ISSUE TITLE
Simple cc.json does not display anything

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#17]
[test.txt](https://github.com/MaibornWolff/codecharta/files/1052519/test.txt)
[test2.txt](https://github.com/MaibornWolff/codecharta/files/1052518/test2.txt)

I generated a very simple json file consisting of only one node and two metrics (blabla and blubblub). When I open this file in the online demo at https://maibornwolff.github.io/codecharta/visualization/app/ it has no selected metrices and it shows two nodes "root" and "Parent Leaf". If I choose one metric it shows nothing.

I also tried a different file with the same result.

**Comment by ukinimod** [comment]
I tried it again with a slightly modified file. It seems there must be at least 3 different metrics otherwise nothing will be displayed. This seems like an unneccessary restriction, but no major issue.

**Comment by silasg** [comment]
Oh yes, had the same issue when I was playing with different sonar metrics.




__________________________________________________

Blockchain: Euphorie oder Schockstarre – mehr in den
Praxis-Tipps https://www.maibornwolff.de/newsletter/1-2017
__________________________________________________

Silas Graffy
Senior IT Architect


Mobil +49 151 544 22 047
silas.graffy@maibornwolff.de
Baseler Straße 10, 60329 Frankfurt am Main

MaibornWolff GmbH, Theresienhöhe 13, D-80339 München
http://www.maibornwolff.de, Telefon +49 89 544 253 000
USt-ID DE 129 299 525, Amtsgericht München HRB 98058, GF:
Volker Maiborn, Holger Wolff, Jens Rieger, Alexander Hofmann

__________________________________________________

On 7. Jun 2017, at 21:25, Dominik Ufer <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried it again with a slightly modified file. It seems there must be at least 3 different metrics otherwise nothing will be displayed. This seems like an unneccessary restriction, but no major issue.

**Comment by mrpatpat** [comment]
Thank you for your contribution ! 
I am currently developing a solution to this problem on [this branch](https://github.com/MaibornWolff/codecharta/tree/mapsWithLessThanThreeMetrics). I will propably create a pull request today.
