### ISSUE TITLE
Hovered packages should be clearly visible

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#176]
## Description

Hovering over a package should make the package clearly visible (f.ex. by making it white, creating a spotlight, highlighting all children). This is half-implemented currently. Some packages are not clearly white when hovered and instead just a lighter shade of brown. 

Use creativity and see what works on small and big maps (firefox.json).

**Comment by mrpatpat** [comment]
Advice for the person who will implement this:
Hovering causes the current material to be brightened (Some maths on the color value). To correctly implement this the material needs to get switched with a hover material. Keep in mind that just switching it with white in all cases (red, greem, yellow, highlights, ...) will cause an information loss because the hovered element is always white.

**Comment by mrpatpat** [comment]
@FernandoES are you working on this feature ? If yes, can you assign yourself ? If not I would start this one.

**Comment by NearW** [comment]
@fatihi this issue can be closed, because of the new hovering effect.
