### ISSUE TITLE
Combine coverage of e2e tests with other test coverage

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1878]
# Feature request

## Description

As a developer, I want a combined coverage report so that it's easy to identify parts that are not covered by any test.

## Acceptance criteria
- All tests, no matter which ones create coverage
- All coverage reports are combined into one to show a combined coverage percentage

**Comment by RomanenkoVladimir** [comment]
Sonarqube does not support pupeteer e2e test coverage generation, but I thought we could get it from external sources

I tried to implement it using: https://github.com/istanbuljs/puppeteer-to-istanbul

However it did not increase our code-coverage, while slowing the pipeline down substantially. I therefore only tested it with one class, as I might have choosen the wrong one , it might be interesting to check it out with other files, enabling it for all our e2e tests will make the pipelien run for over 20min, which is unusable.

You can test the current implenetation here: https://github.com/MaibornWolff/codecharta/pull/2331, however you need to merge reports before analysis to get a sonar qube output, else check used artifacts in github actions.

Another option I tried was using https://github.com/ocavue/jest-puppeteer-istanbul, it seemed promising offline, however it broke after the last node 16 update... however it might be interesting to take another look. Although the library seems to be discontinued which should be considered if we were to use it

**Comment by RomanenkoVladimir** [comment]
Feel free to take this issue

**Comment by ce-bo** [comment]
Webpack combines all TS/JS files in one big bundle.js. So it is hard to collect and map coverage back to our original files.
Normally, source maps are the way to go to collect and map coverage back to our files.
Unfortunately, source maps are not supported correctly by jest-puppeteer, so that we are not able to solve this.

Another way to go would be to compile our files using `tsc` command instead of webpack.
We should proof this approach.

**Comment by jannikr** [comment]
@BridgeAR In my opinion, we currently have two possible options to solve this issue. 

1. Wait until the migration to Angular is complete to save duplicate work and think about an alternative to Jest-Puppeteer such as Cypress.

2. Run E2E tests without using Webpack to determine coverage. However, the tests might then have different results with different processing.

**Comment by ce-bo** [comment]
One addition to your second option: We thought that we can compile and sourve our sources with `tsc` instead but this will not work either because jest-puppeteer is obviously not able to resolve source-maps properly at the moment.

Therefore, we should go with option 1 (waiting for the Angular migration and Switch to Cypress).
In the meantime we definitely should continue writing E2E tests with puppeteer.

Let's work on a PoC for the Cypress Migration (#1234).

**Comment by ce-bo** [comment]
@jannikr One addition to your second option: We thought that we can compile and sourve our sources with `tsc` instead but this will not work either because jest-puppeteer is obviously not able to resolve source-maps properly at the moment.

Therefore, we should go with option 1 (waiting for the Angular migration and Switch to Cypress).
In the meantime we definitely should continue writing E2E tests with puppeteer.

Let's work on a PoC for the Cypress Migration (#2410) and close this issue.
