### ISSUE TITLE
Implement generic parser for lots of languages

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1885]
# Feature request

## Description

As a user, I want to be able to analyse lots of languages so that I do not have to search for other tools to identify hot spots in code. To do so, we are able to rely upon e.g., [semantic](https://github.com/github/semantic). It's a generic AST and with the result it would be possible to identify e.g., complexity and much more. The supported languages are quite a few and we would benefit from such an approach. The implementation is likely quite some work though.

## Acceptance criteria

- Semantic works for all supported languages and creates a cc.json file with basic metrics such as MCC

## Assumptions & Exclusions

More metrics can be added later one by one.

**Comment by ce-bo** [comment]
This will not be built on the basis of Semantic. Semantic uses Tree-Sitters node-types.json files to generate Haskel Types for the language expressions of a couple of programming languages. Thus, a generic AST is provided to parse metrics generically. Because only a couple of programming languages are supported and the maintanance of the repository fell asleep, I decided against it.

The current approach is to use tree-sitter directly. Therefore, we can support all programming languages that are supported by tree-sitter with minimal effort.

**Comment by ce-bo** [comment]
This has been implemented as a basis for my master thesis.
You can find the result here: [MetricGardener](https://github.com/MaibornWolff/metric-gardener/).

We can already use the tool like so:
- Clone it
- go to the root folder
- run `npm run start -- parse /path/to/sources -o /output/file/path.json`

There are a lot of open todos. I think the most important ones would be:
- to think about how to publish MetricGardener (e.g. npmjs.com)
- add unit tests for the metrics calculation of all supported languages
Then, we can integrate it in CodeCharta #2619.

Besides of that, a lot of refactoring shoud be applied, I have to add more documentation and technical insights to the README.md file and finally a lot of improvements are still to be done.

**Comment by ce-bo** [comment]
I will work on MetricGardener regulary to solve my open parts.
How to deal with this issue? Back to backlog?

**Comment by ce-bo** [comment]
I close this issue. Let's open new issues to add support for useful command line options when needed. The npm publish is done in #2619.
Further development / new issues for MetricGardener should be tracked in its repository.
