### ISSUE TITLE
Unable to correctly import CSV from Source Monitor

### ISSUE THREAD

**Issue by silasg** [MaibornWolff/codecharta#1886]
# Bug

GIVEN
Source Monitor CSV exported using current source monitor version for a Delphi code base containing data about one checkpoint with n files (n >> 1)

WHEN

ccsh csvimport my.csv -o mymap.cc.json

THEN Current
Created Project with 1 leaves.

THEN Expected
Created Project with n leaves.

Research shows that the CSV header did not contain "Path" like expected by import filter but "File Name". Changing the header manually fixes the issue. Proposal: check if the header is related to Source Monitor version and change the hard-coded expectation or (better) add a command line switch to overwrite which column to use for node name.

- CodeCharta Version: 1.68
- OS: MacOs
- Browser: -

**Comment by ollio** [comment]
@silasg do you can attach the example csv where the error occurs?

**Comment by silasg** [comment]
@ollio it was confidential customer data ;/

**Comment by ce-bo** [comment]
Let us ask the user for the name of the file name/path column.

**Comment by Hall-Ma** [comment]
@ce-bo 
Jan and I did some research about this issue. First of all, the user should use our `sourcemonitor importer`, when he has a CSV file made by SourceMonitor. Because this importer expects 'File Name' as a part of the header and it works as expected.
Additionally, we have the `csv importer` which expects 'Path' as a part of the header, and because of this, it can't parse a CSV file from SourceMonitor correctly at the moment. 
Interestingly, the `csv importer` and `sourcemonitor importer` use the same single CSV file as test ressource, but we have only 'Path' as the header.
Why do we have two (not really) different CSV importers for the same thing? We could save resources if we would maintain only one importer and handle the naming of the header in the code differently (with or without asking the user).
What are your thoughts?

**Comment by ce-bo** [comment]
- The SourceMonitorImporter has custom logic (e.g. to rename column names and to produce a special output csv file). The import is not done by the SourceMonitorImporter itself, it just uses CSVImporter for that. For now I would not invest time to merge the two importers. If we would have only one CSVImporter we still would need a kind of an adapter to implement the column renaming logic.
- Let's add a new option to the CSVImporter to specify the path column name, so that the user is more flexible during the import.
- I assume that the path column name for SourceMonitor CSV files keeps stable. If so, we do not need to add the option to the SourceMonitorImporter.
- As you mentioned, please improve the unit test

**Comment by jannikr** [comment]
We should not forget to adapt or improve the documentation after the changes so that misunderstandings do not occur again on this topic.
