### ISSUE TITLE
make it easier to find out to which package/folder a class belongs

### ISSUE THREAD

**Issue by silasg** [MaibornWolff/codecharta#20]
two ideas for this goal (both could be implemented, it's not an xor)

1. add a slider or similar to change the margin/padding between buildings. then it would be easier to hover the ground of a block
2. add a tooltip for the name of the selected block showing the complete path and not only the leaf element.

**Comment by ukinimod** [comment]
Thank you Silas for your suggestions. We are considering another option that adds an additional view displaying the hierarchical structure. I also think we should improve the visability of the packages.

**Comment by ukinimod** [comment]
There was another request from a user for a feature like that.

**Comment by mrpatpat** [comment]
In #37 we implemented a margin slider. In general, it works. Problems appear as soon as you turn the margin value higher than the half of the shorter side of a building. This causes the building to disappear since the margin overlaps the building size. The margin actually is more like CSS padding in this case. 
Before releasing this feature we need a way to handle this problem. 

We could (in no particular order): 
* Just accept it 
* Limit the margin slider according to the shortest side of a building
* Limit the slider to "small" values and accept that some "small" buildings disappear
* Increase district/folder area while increasing building margin and therefore acting like CSS margin
* Something else ?

**Comment by silasg** [comment]
Don`t know the implications to implementation and effort but why not leaving the building sizes as they are and just *adding* more space around the elements?

**Comment by mrpatpat** [comment]
Full paths in details are now implemented. This will be part of the next release.
