### ISSUE TITLE
Scenarios should only be about metrics

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#224]
# Feature request
As an auditor, I want scenarios that help me select important metric combinations in one click, so I can quickly switch between different views.

Currently the scenarios reset everything, including weird things such as margin. That is confusing and does not reflect what I want. 

To be usable the scenarios should only be about metrics. The coverage scenario, for example, should only set the three metrics and the color range. A building with >= 80% coverage should be green. A building with >= 20% coverage should be yellow. All other buildings red.

**Comment by mrpatpat** [comment]
This is an important request since the old "logic" does not match the current needs. I also think we should not limit ourselves to certain settings. We should  implement it like an update object which is a partial settings object. The creator (the programmer at the moment) of the scenario can decide which settings are a part of the scenario.

**Comment by Richargh** [comment]
I don't know what all this techno babble means :) 

Seriously though, as a user of CC I want scenarios that help me select important metric combinations in one click. In the future these scenarios might be customizable (not know though). I don't need it for other settings.

**Comment by Richargh** [comment]
I don't know what all this techno babble means :)

Seriously though, as a user of CC I want scenarios that help me select important metric combinations in one click. I don't want to have to finely tune every metric, every time I open CC. I don't need it for other settings.
