### ISSUE TITLE
Improve UI of Map Configurations Component

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2462]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a User, I want a pretty, nice and understandable UI, so that it makes sense for me to use the feature.

# Developer Notes

That is a requirement to release the feature as stable.

**Comment by jannikr** [comment]
When this Issue ist closed, we are planning to remove the download button in the top left corner of the viewport. This version would otherwise repeat the functionality of the download button:
<img width="683" alt="Bildschirmfoto 2021-11-08 um 16 31 13" src="https://user-images.githubusercontent.com/31436472/140770550-652f30bf-3cfe-4abf-b9b7-837e591afcd0.png">
