### ISSUE TITLE
Are attributes in cc.json necessarily numbers?

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#247]
# Question

I was working on the jasome integration and what irritated me is the fact that attributes of nodes (and edges) seem to be necessarily numbers (numbers in Strings are also not allowed). In the analysis part this restriction is not implemented. I think this is a major point that should be solved either by making the interface more permisive or by changing the producers. There is even code in the analysis to deal with non-number attributes.
Actually I don't think that the interface was restricted this way in the beginning. So it is actually a breaking change. Is there a critical reason why jsons with non-number values should not be accepted?

**Comment by mrpatpat** [comment]
Hi, this should indeed be solved. It is not yet a critical problem, but it may become one. i looked into the history of the [shema file (initially 2 years ago)](https://github.com/MaibornWolff/codecharta/blob/574ca9de946ea1c56d8a9ffe3c50832c94b5e323/visualization/app/codeCharta/core/data/schema.json) and it was defined as a number at the initial point. I cannot remember how it was before that. I *think* it happened like this: 
* There was no schema json, just example json files and maybe some docs
* I created one in order to simplify file validation (no more manual checking for properties etc.)
* It was accepted (?) and no one, including me, realized this restriction because it validated all existing files correctly *or* there were reasons and we simply forgot it

To achieve compatibility I personally would like to add different types. On the other hand this makes things complicated since we need some kind of type property on attributes because json does not know others than number and string (afaik).  

In order to  keep the discussion in one thread I will close this issue and continue it in #182.
