### ISSUE TITLE
Improve Changelog Format and What's new feature 

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2497]
# Feature request

## Improve Changelog Categories
@shaman-apprentice suggested to change the changelog categories from:
`## [unreleased] (Added 🚀 | Changed | Removed 🗑 | Fixed 🐞 | Chore 👨‍💻 👩‍💻)`
to the following:
`## [unreleased] (Added 🚀 | Changed | Deprecated | Removed 🗑 | Fixed 🐞 | Security)`

Personally, I would keep the categories as they are. A removing change will most probably affect the UI only, so Removed would be the more appropriate one. However, I like his suggestions to add Deprecated to cover it for future cases.
So, how about?:
`## [unreleased] (Added 🚀 | Changed | Removed 🗑 | Deprecated | Fixed 🐞 | Chore 👨‍💻 👩‍💻)`

Furthermore, we should describe in the Changelog, that we differ a bit from [keepachangelog](https://keepachangelog.com/)

## Improve What's new feature
The feature should automatically discover new categories in the changelog, so that the feature won't break on those changes.

## Development notes (optional Task Breakdown)
- [ ] We could try to write a unit tests that reads the "## unreleased..." line at the top of the changelog and checks if thre right categories are given.

## Acceptance Criteria
- New/Removed Changelog Categories will be discovered automatically by the What's new feature.
- Changelog Categories are adjusted as discribed/discussed in this issue
- All Changelog entries follow the new structure.
- KeepAChangelog description in CHANGELOG.md explains that we differ a bit from that format.

**Comment by shaman-apprentice** [comment]
I personally thing, we shouldn't state, that we differ from keepachangelog, but just remove the reference. 

I think we still fulfill the spirit of keepachangelog and some explanation why we don't comply completely only distracts without match value.

**Comment by BridgeAR** [comment]
Our changelog is of course meant for humans. That's why we use that information for the "what's new" part when opening a new CodeCharta version. I doubt that we gain much by changing the entries and I would not want to invest much energy into this topic. The security part is something we would mention, if it's applicable and we mostly do not have deprecations. Such entries should also always explicitly be mentioned.  "Keepachangelog" suggests a specific format and our entries are indeed "based" upon that. We do not mention that we follow it strictly. As such, I am going to close this as won't fix.
