### ISSUE TITLE
Set 'Save As' File button in browser and native app

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#251]
# Feature request

## Description

- Instead of only downloading a file when clicking on the save-button (in the top left corner), the use should have the ability to "save as" the file to a place in the filesystem he chooses.
- Inside the native app the use is supposed to have two options.
    - Just "Save" the file, which was opened from the directory (Replace used file or add a second file?)
    - Or select a new file system directory via a "Save As" button

**Comment by alexhunziker** [comment]
Just FYI: We (Ben and I) did a Spike some month back, where we checked how to realize different behaviour on the desktop (node.js) and the browser version. This might be useful for this issue and #686 and #687. The differentiation might be necessary since the browser limits certain functionalities due to security reasons.

https://github.com/MaibornWolff/codecharta/tree/spike/323/standalone-only-features

**Comment by Quicano** [comment]
The way I see it this issue might not be solvable, since, as @alexhunziker mentioned, the browser funcionalities are limited in this regard. This stackflow link affirms that javascript is not capable of accessing the local filesystem beause of the sensible data that could be read or saved. 

[https://stackoverflow.com/questions/9840923/get-browser-download-path-with-javascript/9840961#9840961](url)

**Comment by Quicano** [comment]
Either way, my work was not in vain since I was able to reduce one rather long code snippet into to lines of code: 

const blob = new Blob([dataJson], { type: "text/json" })
		const mouseEvent = document.createEvent("MouseEvents")
		const link = document.createElement("a")

		link.download = fileName
		link.href = window.URL.createObjectURL(blob)
		link.dataset.downloadurl = ["text/json", link.download, link.href].join(":")
		mouseEvent.initMouseEvent("click", true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null)
		link.dispatchEvent(mouseEvent)


can be reduced to: 

		const blob = new Blob([dataJson], { type: "text/json" })
saveAs(blob, fileName);

**Comment by BridgeAR** [comment]
Closing as this is going to be obsolete after implementing the custom configs feature.
