### ISSUE TITLE
Labels disappear after increasing the height

### ISSUE THREAD

**Issue by Shivan-997** [MaibornWolff/codecharta#2517]
# Bug

## Acutal Behavior

a visualized cc.json is opend. after increasing the height:
Labels disappear (Screenshot 1)
when click on a building you can see the label
Label appear (Screenshot 2)

## Expected Behavior

a visualized cc.json is opend. after increasing the height:
Labels are shown

## Screenshot
#Screenshot 1
<img width="1001" alt="Screenshot 2021-11-19 at 16 13 32" src="https://user-images.githubusercontent.com/57844849/142645846-71522707-1d76-4e5c-8fe5-b8dcee0c9994.png">

#Screenshot 2

<img width="1189" alt="Screenshot 2021-11-19 at 16 16 44" src="https://user-images.githubusercontent.com/57844849/142646327-afedff49-09be-44cf-aabd-b4041f0e7b0a.png">

**Comment by ce-bo** [comment]
Increasing the height of the buildings also increases the height/position of the floor planes, so that the transparent floor label plane is covered.  

Regarding Screenshot 2: This happens only if you first increase the height and then increase the number of drawn labels (slider). It seems that the combination of increased building heights and changed number of labels (slider) causes the displaced label texts.

**Comment by ce-bo** [comment]
Please check, if this issue can be closed.
There a still some minor issues open (adressed in #2770).
