### ISSUE TITLE
Error on Focus missing buildings

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2616]
# Bug

## Expected Behavior

GIVEN
loaded codecharta.cc.json with missing building for `sortByMetricName.ts` due to too less map space

WHEN
open the file explorer / tree map then open context menu for `sortByMetricName.ts` and click "focus"

THEN
to be discussed (no buliding, no focus effect?)

## Actual Behavior
a console error occurs

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/150306967-bcbe7eec-4c9b-4814-ab33-e008dfe45652.png)
![image](https://user-images.githubusercontent.com/26900540/150306826-63547799-8fe7-4582-b2f3-23255f5e7ecb.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes | no
- CodeCharta Version: 1.87.1
- OS: all
- Browser: all

**Comment by BridgeAR** [comment]
The error should be very straight forward to get rid of (just make it optional).
However, I suggest to do something different: check if a file is actually rendered or if it's invisible. If it's the latter, do not show the regular dropdown but instead, let the user know that the file is not visual due to being empty (or very small).

After fixing the margins this should only apply to empty files.

**Comment by ce-bo** [comment]
This will be resolved by #3123 and #3113.

**Comment by ce-bo** [comment]
This bug is fixed as mentioned above.
