### ISSUE TITLE
cssh check command throws exception

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2704]
# Bug

## Expected Behavior

<GIVEN>

WHEN executing `ccsh check <path/to/valid/cc.json>`

THEN the the ValidationTool should display either that the file is valid or a pretty error message

## Actual Behavior
an exception with no concrete validation results is thrown for actually valid cc.json files (e.g. the current codecharta.cc.json file downloaded from Web Demo). I think the JSON Schema which is used for validation is not up to date (`analysis/tools/ValidationTool/src/main/resources/cc.json`).

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/157009975-ea8850a4-cacc-46d3-96c8-802e8a82057d.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.91.0
- OS: all

**Comment by Chrisp485** [comment]
The Exception is caused, because after downloading from the visualiazation the format of the cc.json  is changed <br> 
![Screenshot 2022-06-03 155052](https://user-images.githubusercontent.com/45608151/171876574-b951589a-1532-4db4-8ef2-de31e96588c8.png)

In the future, when global configs will be available across the app the download button will be removed.
