### ISSUE TITLE
Expand directory summary for delta mode

### ISSUE THREAD

**Issue by Hall-Ma** [MaibornWolff/codecharta#2708]
# Feature request

## Description

As a user, I want to see the number of changed files in a selected folder next to added and removed files in delta mode so that I get a quick overview of the dimension of the changes of both maps.

## Acceptance criteria
- UI suggestion
  ![image](https://user-images.githubusercontent.com/72517530/157488960-ac3a898c-7745-4c00-9d7e-a984419b29ae.png)

## Development notes (optional Task Breakdown)
- [ ] check every node, when a delta value is not equal to 0 then there is a changed file
- [ ] add a new property to `fileCount` property in `squarifiedNode`

**Comment by knoffi** [comment]
Question about the UI suggestion:
The blue number equals 4 because of  ( 1 - (-1) ) ^ 2 = 4 ?

(Or in other words, the blue number equals the square of changed files?

**Comment by BridgeAR** [comment]
@knoffi green represents all newly added files. Red represents removed files and blue represents existing changed files that were not removed.

**Comment by knoffi** [comment]
@BridgeAR Thanks for the fast reply. So the black text "5 files" stands for the number of changed files, and thus "blue = 5 - 1"?

**Comment by BridgeAR** [comment]
No, there is no real correlation between the entries. Black represents the total number of files. Blue is the number of changed files (a subset of black).

**Comment by knoffi** [comment]
Finally, I fully understand my confusion:

In the description, it is stated: "... when a delta value is not equal to 0 then there is a changed file." This refers to the property in
`interface squarifiedNode {
	...
	deltas?: {
		[key: string]: number
	}
	...
}`

I thought that the description was refering to the _displayed_  values "∆1 | ∆-1 " , because "∆" is a big delta letter. Thus, I was assuming there was some correlation between them.
