### ISSUE TITLE
Remove Invert Height option  in Delta Mode

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#277]
# Bug

The actual behavior detailed below is a bug. Please remove invert height option from delta view. We'll probably not need it.

---------

## Expected Behavior
Assumption: Delta mode and Invert Height are selected
- the overall node height (grey+color) should get inverted
- the split colors grey+green or grey+red should keep the same ratio as before

## Actual Behavior
Assumption: Delta mode and Invert Height are selected
- Only the grey node height gets inverted
- The green or red block is just added on top of the grey node with the same height as before

### Screenshots
Delta Mode, normal Height
<img width="45%" src="https://user-images.githubusercontent.com/23529226/48353822-3db4cd00-e688-11e8-95c6-a3bfe9c14862.jpg"> <img width="45%" src="https://user-images.githubusercontent.com/23529226/48357730-28906c00-e691-11e8-8983-9c04e72e268f.jpg">

Delta Mode, Invert Height
<img width="45%" src="https://user-images.githubusercontent.com/23529226/48353826-3db4cd00-e688-11e8-9f75-b02bcb5160a1.jpg"> <img width="45%" src="https://user-images.githubusercontent.com/23529226/48357718-24fce500-e691-11e8-8d30-8bcfd661e5f1.jpg">

## Steps to Reproduce the Problem
  1. Open RibbonBar and switch to Delta Mode
  2. Select a second comparison map with different metric-values
  3. Now the map looks as expected
  4. Select `Invert Height` in RibbonBar
  5. Now the map looks kinda weird as the grey boxes get inverted, but the delta boxes above just keep the same height

## Specifications
  - Version: 1.19.0

**Comment by Richargh** [comment]
This is a strange problem. The green values are completely flat, only the red ones are affected this way.

**Comment by alschmut** [comment]
@all I just thought about how I would like the buildings be represented in "delta invert height"-mode and to be honest, either I a just don't get it at the moment or there is not even a use case for inverting the delta nodes. Why do you want to see the metric-changes of a building inverted and what kind of information does it then represent? Can somebody help? From my point of view, we could just disable the invert height button for the delta mode.

**Comment by Richargh** [comment]
Suppose 
* we put code coverage on the height metric
* we have a map where almost all buildings have a high coverage
* we want to see which buildings with low coverage have improved
*we select delta mode

The buildings we are interested in
* `Foo.java` which used to have a coverage of 0, but now has a coverage of 20. 
* `Bar.java` which used to have a coverage of 100 but now has a coverage of 0.

In regular mode **`Foo.java` has a height of 20, all green** and **`Bar.java` has a height of 0, all red**. Foo is hidden because there are lots of much bigger buildings around it with high coverage.

In delta mode **`Foo.java` has a height of 80, all green** and **`Bar.java` has a height of 100, all red**. Both are now visible because the buildings with high coverage are now completely flat.


Does that example clear up the confusion and why we want delta mode with inverted height?

**Comment by Richargh** [comment]
The Solution: disable invert height for delta buildings.
