### ISSUE TITLE
Delta Mode not working for codecharta.cc.json

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2789]
# Bug

## Expected Behavior

GIVEN
- current codecharta.cc.json
- old map: Unzip and upload: [codecharta_2022-04-28_08-53.cc.zip](https://github.com/MaibornWolff/codecharta/files/8581208/codecharta_2022-04-28_08-53.cc.zip)

WHEN
comparing them in the delta mode

THEN
I can see the actual deltas.

## Actual Behavior
the two maps are shown side by side and no deltas are shown

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/165716677-68a2fe25-6032-47b7-a350-22b8b909dd3c.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes
- CodeCharta Version: 1.95.2
- OS: all
- Browser: all

**Comment by knoffi** [comment]
That's not a bug, that's a feature! Or at least it is a feature which we can improve.

The problem seems to be the following:

The built-in `codecharta.json` has a root folder with name "root". And "root" has one child with name "app".

The uploaded cc.json-file has a root folder with a __different__ name: "root/app".

Our frontend compares the name of both root files and only sees `"root" !== "root/app"`.

I see two potential fixes here:

### The user-friendly one

When we compare two file with different root names, then we should inform the user about this. A small pop-up message containing
"The root folders ("root" vs "root/app") are different. These projects are not comparable!" would do the job.

Users would also benefit from it if they accidentally compare two projects with different root folders. This would spare them the hazzle when they overlook the obvious. Thus it would boost the UX of our project. 

Also, in the future, we could give the pop-up message a small button "Adjust root" which makes the frontend act like both root folders had the same name.


### The hacky one

We can also extend our logic so that the frontend handles this __specific__ case:
Instead of comparing the names of the root folders, we simply compare their "collapsed" names.

I.e., If "root" just contains the folder "app" which just contains the folder "src", while "src" has more than one child, then the "collapsed" root name would be:
"root/app/src"

**Comment by knoffi** [comment]
## UPDATE

I tried the above appraoch "The hacky one". And it seems to work so far.

Next, I will try if it works with two small example files which contain edge metrics.

I am a little bit worried that if we enable DeltaMode for the above scenario, that another part of the logic will run into an unexspected case and thus break.

**Comment by ce-bo** [comment]
This issue will not be fixed. This bug is produced by comparing maps with different structures. So it is fine, that the two compared maps are not shown in delta mode, even if they are very similar. It would take to much effort to refactor the code parts. So I close this for now
