### ISSUE TITLE
Area, Height and Color Metrics are resetted on file uploads

### ISSUE THREAD

**Issue by shaman-apprentice** [MaibornWolff/codecharta#2826]
# Bug

## Expected Behavior
~~Given I change the default area, height and color metrics
When uploading a new file
Then the previous changed area, height and color metrics are still selected.~~

Given I change the default area, height and color metrics
When uploading a new file
Then the default scenario is applied if applicable and otherwise the first available metrics are taken for area, height and color.

## Actual Behavior
When default scenario is not applicable, then the metrics are not defaulted.

## Steps to Reproduce the Problem
1. Change area, height and color metrics to function in https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json
2. Click on "Load cc.json files" button in top left and upload file from local dev demo

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json&file=codecharta_analysis.cc.json): yes 
- CodeCharta Version: 1.97.0

## Analysis
This was introduced with https://github.com/MaibornWolff/codecharta/pull/2827

**Comment by BridgeAR** [comment]
Each .cc.json has indivdual metrics. We can't always use the metric that has been selected last as it might not exist. Uploading (and visualizing - that's actually the important part, not the upload itself) a new file should as such reset the metrics to their defaults due to probably not being related to the former .cc.json or to contain different metrics.
We could add a global option to let the user define the behavior but it's probably not critical and adding more knobs is not ideal.

**Comment by shaman-apprentice** [comment]
The status quo was as followed:

The code which checked, if the previous selected metrics are still available was already there plus an unit test for it.

But the logic didn't matter, as CodeChartaService's `setDefaultScenario()` always resetted it first and then the logic of the related metric service checked if the new (resetted) metric does still exist. The test still passed, as the update function was mocked away.

I agree that this is not an important feature. That's why I didn't fixed it immediately in the migration, but created this ticket first for discussion. So I vote for closing this as won't fix, as this previous broken implemented feature is discussable.

**Comment by shaman-apprentice** [comment]
I just checked the code. If you (@BridgeAR) agree please assign this ticket to me first. There are two little helper function we can remove in this case first.

**Comment by BridgeAR** [comment]
> The code which checked, if the previous selected metrics are still available was already there plus an unit test for it.

I do not know where the code checked the previous selection. Can you point me to that code? :-)

> [...] CodeChartaService's setDefaultScenario() always resetted it first and then the logic of the related metric service checked if the new (resetted) metric does still exist. [...]

If I understand you correct, that's the correct behavior. First, we reset the metrics to our internal defaults (rloc, mcc, mcc, rloc). Then we check if they actually exist and use a fallback, if they do not exist. It would of course be possible to directly check if the default exists and use a fallback in the first step instead of separating that.
