### ISSUE TITLE
Creating .cc.json Files not possible anymore

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#2850]
# Bug

## Expected Behavior

WHEN
`npm i -g codecharta-analysis`
`ccsh sonarimport https://sonarcloud.io/ maibornwolff-gmbh_codecharta_visualization -o cc-viz-2`

THEN
the output file should be created.

## Actual Behavior
the process is hanging up and no zip file is created.

## Notes:
Version 1.97.0 is working properly:
`npm i -g codecharta-analysis@1.97.0`
`ccsh sonarimport https://sonarcloud.io/ maibornwolff-gmbh_codecharta_visualization -o cc-viz-2`

## TODO:
Please check other ccsh commands, so that they are working properly.

**Comment by phanlezz** [comment]
Sourcecodeparser doesn't work either. I revisited some old versions, and it stopped working after my commit 😞 :

[Fix/2580/make sure all command line tools understand gz files](https://github.com/MaibornWolff/codecharta/commit/23d35a2a35ee7a5ee323b95dcb81f9dd11a7f372)

I'm not sure what the issue is at the moment, but both sonarimporter and sourcecodeparser stopped working on this commit. Before they worked as intended. 
Note: sourcecodeparser is stuck **before** the `Created Project with xx leaves.`, sonarimport is stuck **after** the line. (not sure if relevant)
