### ISSUE TITLE
SPIKE: add features that are only displayed in the Standalone CodeCharta

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#323]
This is a [SPIKE](https://www.mountaingoatsoftware.com/blog/spikes). 
```
A spike refers to a **time-boxed research** activity to gain technical knowledge. No commits to master. It can be done as a branch or completely separate code base. Unlike a regular feature it is done once the time-box is done. And the code can be thrown away once the knowledge is extracted.
```

We want to explore how we can add features that are only displayed in the Standalone CodeCharta application. Please try:

* adding a button/searchbox/widget only to the standalone (f.ex. some functionality is only in standalone)
* Change any background color only in the standalone (f.ex. we can customize the view in standalone)
* Access the file system or network without user input only in the standalone (f.ex. we might save automatically in standalone or double-click a building and open an IDE) --> this one is important, because we cannot do that in the browser

The timebox is 2 days. Afterwards we should discuss if we know enough or should extend the timebox.

**Comment by alexhunziker** [comment]
What we have learned so far:

## Determining if Standalone
* The code snippets that ckeck for a node environment seem not to work for codecharta (always false)
* It is possible to set an environment variable to the "npm run build" and "npm run serve" commands, these variables can be used to alter webpack config and (more importantly) with the define plugin can be passed to the application
* These variables are then accessible as global variables in the application `declare var STANDALONE:string`

## Functionality in Standalone
* In the standalone we can provide functionality not available in the web-version
* We have access to the file system (read/write)
* We can open files/folders in the browser view
* We can open files/folders with the default applications on Windows/Mac (though the commands differ) with child_process
* We can access the current absolute path with "path"
* We can write to a specific path on the disk with "fs"

## Persisting Problem
* Pipeline is still red, because some e2e tests fail. I think the problem might be, that the require() command in the node spike leads to an exception on the CI... Locally there are no errors on my system, but the same error as in the CI happens on Jaisons PC
