### ISSUE TITLE
Use current working directory as default path for file input

### ISSUE THREAD

**Issue by moritz-suckow-mw** [MaibornWolff/codecharta#3274]
# Feature request
## Description

As an Auditor, I want to enter an empty string when trying to analyze the current directory so that I do not need to manually find out and enter the path myself. 

## Acceptance criteria
- When using the interactive shell
  - the default for input path is the current directory
  - the users full/absolute current working directory is shown as a hint' in the shell when the question is shown to the user, so that they can accept it by pressing enter
  - This should be implemented for all applicable parsers (but this may apply only for certain parsers)
  - If a parser expects only a path to a single file, then just a file path example is given as a hint but no directory path as default.

**Comment by ce-bo** [comment]
@moritz-suckow are there any questions?

Ideally, a hint is shown that the current working directory is used as the default when not specifiying any path.

**Comment by moritz-suckow** [comment]
Do we implement this for all parsers who can receive a directory as input or just the RawTextParser?

**Comment by moritz-suckow** [comment]
Additionally I had some doubts if this made sense to implement since this could introduce some problems, because of how the interactive shell currently works with copy-pasted input. It sometimes happens, that when you paste something into the shell that the input is automatically entered, sometimes even the input after the current question. What this could mean is, that if you do not watch out you could get your current working directory completely parsed.

**Comment by moritz-suckow** [comment]
I updated the issue to include the decision from the weekly!
