### ISSUE TITLE
Web Demo broken on Apple (Safari, Chrome, Edge)

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3330]
# Bug

## Expected Behavior

<GIVEN>

WHEN visiting the [web demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz)

THEN I can use it even with Safari

## Actual Behavior
a white page is shown

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: 1.117.0
- OS: Apple (Desktop and iPhone)
- Browser: Safari

**Comment by moritz-suckow** [comment]
I just opened the web demo with safari and everything works as expected. Although in the past I have had a lot of trouble trying to use the web demo with safari and experienced the behaviour described here a lot of times. 
Did you open this issue because of my troubles or because there were other affected users?

**Comment by ce-bo** [comment]
I have opened it because of your report and my experience when opening the Demo with an iPhone.

**Comment by ce-bo** [comment]
Since the Web Demo seems to be working on your machine, I will decrease the priority.

**Comment by MO2k4** [comment]
@ce-bo @moritz-suckow the page cant be opened via safari or Edge on my end

the logs show the following errors

```
THREE.WebGLRenderer: Error creating WebGL context.
ERROR Error: Error creating WebGL context.
```
