### ISSUE TITLE
Turning off global option 'reset camera when changing maps' breaks camera 

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3478]
# Bug

## Expected Behavior

<GIVEN>

WHEN

Turning off this global option and reloading the page

THEN

The camera returns to the last position and orientation

## Actual Behavior

Camera gets put into a default position (likely aimed at world center)

## Screenshots
<img width="1512" alt="image" src="https://github.com/MaibornWolff/codecharta/assets/105795397/82aacc7a-52c2-46c1-bdb8-394dc99c8449">

## Steps to Reproduce the Problem
1. Turn off setting in the global config menu
1. Reload 
1.

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes | no
- CodeCharta Version: 1.122.0
- OS: MacOS
- Browser: Yes

**Comment by IdrisLaabidi** [comment]
It seems there's some confusion regarding the expected behavior. The expected behavior should not be that the camera returns to the last position and orientation upon reloading the page. Currently, there is no implemented code that achieves this. Instead, the camera should fit the scene when reloading.

**Comment by IdrisLaabidi** [comment]
However, we could add a new global option called `safeReload`, which will preserve the camera's position and orientation when reloading the page. For now, it's expected that the camera defaults to fitting the scene.
