### ISSUE TITLE
cc.json[.gz] is empty

### ISSUE THREAD

**Issue by christianbaumann** [MaibornWolff/codecharta#3487]
# Bug

## Expected Behavior

WHEN I run `cssh tokeiimporter myproject.tokei.json -o myproject.tokei.cc.json`

THEN a valid `myproject.tokei.cc.json[.gz]' is created

## Actual Behavior
The  'myproject.tokei.cc.json` is empty

## Steps to Reproduce the Problem
[5 min Generic Metrics Quickstart](https://maibornwolff.github.io/codecharta/docs/quick-start-guide/#5-min-generic-metrics-quickstart)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): no
- CodeCharta Version: 1.122.0
- OS: Win 11
- Browser: Chrome

PS.: Feel free to contact me via MW Teams. ;-)

**Comment by phanlezz** [comment]
I did some digging and I think, that there might be a problem with the produced paths by Tokei under Windows.
Our Importer seems to struggle with them, and not parse them correctly as paths, but as file names.

**Comment by phanlezz** [comment]
As a quick workaround: It should be possible to replace all `\\` with `/` inside the Tokei JSON file and then import it.

**Comment by christianbaumann** [comment]
> It should be possible to replace all \\ with / inside the Tokei JSON file and then import it.

I confirm that this works.

**Comment by phanlezz** [comment]
I did some more testing:
Tokei used double backslash as path-separator on Windows. When imported with our module, this must be specified with a single backslash. Furthermore, the single backslash can escape the last quotes `"` which can lead to miss interpretation of the entered command. 
It is possible to remove the quotes. 
I will try to improve our importer here, so that double backslashes can be understood correctly or the separator could be determined automatically
