### ISSUE TITLE
Re-Activate Metric-Gardener after a new release `metricgardener` and Node20 Upgrade

### ISSUE THREAD

**Issue by phanlezz** [MaibornWolff/codecharta#3547]
# Re-activate the Metric-Gardener on-the-fly execution `metricgardener`

... as soon as a new version is released on `npm`, which removes the dependency on deprecated `zlib`.
And Codecharta upgrades to Node version 20

## Acceptance criteria
- Remove all mentions of temporary removal
- Re-add it to the `Dockerfile` from analysis as a `npm` install
- Reverse the code changes in the importer and remove the associated test
- Activate the old tests
- Check docker execution!

## Dev Notes

Relevant PRs: #3542 #3545

**Comment by phanlezz** [comment]
Metric Gardener released its version `1.0` so this issue is not blocked anymore.

**Comment by Nereboss** [comment]
After trying this out, there are some problems that prevent us from reactivating it:
- MG requires node v.20 in their package.json while we only require node v.18.
- MG uses features of typescript 5.3, which are incompartible with node v.18 (tested on node v.18.18), so ignoring the incompatible version does not work.

We should discuss the best way to handle this, maybe including someone from the MG team to find out if its feasable to reduce their requirements to node 18. This issue is being blocked until this has been discussed.
