### ISSUE TITLE
Show authors and main author per building in CC

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#363]
Codemaat has a feature that displays which author has worked on which file at what point in time. How can we display and store this?

Codemaat also displays which user is the main author of a file, i.e. has the most commits per file. How can we display and store this?

We can get this data from codemaat, it's just how we can store it in the cc.json and visualize it.

**Comment by alschmut** [comment]
An option to show the different main-authors could be to use the `main-author` as colorMetric and give every main-author a unique color. So you see the **distribution of authors**. As the main author is just one "person" we can store it as a normal attribute (with the only difference of being a String instead of a number). 
To keep it generic: The rendered CodeMapNodes actually knows nothing about the author-names. It would just do the following task: **unique strings get a unique color** and the buildings adopt these colors. This means the buildings use multiple generated colors, instead of the green/yellow/red colorRange.

**Comment by Richargh** [comment]
That would probably be the easiest solution. It would break forwards compatibility (an old version of CC can't load a new cc.json) but not backwards. And we could use the feature in other ways as well. To add a visualization for different languages.

**Comment by NearW** [comment]
But is the main author really the person with the most commits on a file?
Someone who edits 2 lines of code in 5 different commits again and again would be the main author instead of someone who coded the whole file in one commit for example.
This would require programmers to commit very frequently. I feel like the lines of codes you changed in a commit should also be valued here.

**Comment by Richargh** [comment]
The metrics in this case are generated by [code-maat](https://github.com/adamtornhill/code-maat) and that tool analyzes a git log file. You can build it yourself if you have the Clojure build tool [leinigen](https://leiningen.org/) installed. 

```bash
git log --all --numstat --date=short --pretty=format:'--%h--%ad--%aN' --no-renames > codecharta.log
./codemaat.sh -l codecharta.log -c git2 -a main-dev > codecharta.maat.csv
less codecharta.maat.csv
```
For cc that result is:

entity,main-dev,added,total-added,ownership
.gitignore,AdrianE,296,313,0.95
.travis.yml,mrpatpat,220,324,0.68
analysis/filter/EdgeFilter/src/main/kotlin/de/maibornwolff/codecharta/filter/edgefilter/EdgeFilter.kt,alschmut,82,82,1.0

etc.

**Comment by Richargh** [comment]
This discussion has moved somewhat to #678 so we'll close this issue
