### ISSUE TITLE
Improve SteetMap and TreeMapStreet Layout

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#3653]
# Feature request

The StreetMap and TreeMapStreet are important layout algorithms because they are refactoring-stable and provide slightly-better view of the logical structure (how the developers grouped code). They haven't received much love so far compared to the Squarified TreeMap and are still more or less experimental. Let's change that.

## Description

As a user, I want a clearly arranged CodeMap, so that I can see all the important information and i looks nice.

## Acceptance criteria
- [x] Streets get thicker dynamically by the directory size which it represents
- [x] Buildings get higher dynamically
- [x] Files show up first on a street and directories come after that

**Comment by nxdxnx** [comment]
For the beginning I just thickened the root/direct child of root street. It depends on whether there is a root file or not.
In addition I changed how the height scale is calculated. Now it´s dynamic and depends on the number of files in the repo, so that you can see the height differences even on very large street maps.
![image](https://github.com/MaibornWolff/codecharta/assets/152617178/e67830ce-7064-47f0-9a1f-6b6abc8474c8)
![image](https://github.com/MaibornWolff/codecharta/assets/152617178/928eab98-1c2c-42e4-b125-9b8b8d19acc4)
