### ISSUE TITLE
Folder Size in Treeview

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#380]
The Treeview is difficult to use currently. It's difficult to see at a glance how important a folder is. 

It would be nice to see the size metric sum per folder (size metric is usually rloc) in brackets after the folder name. Empty folders with a size metric of 0 should be shown as gray/transparent. The result could look like this (folders with content are marked as fat due to markdown limitations):

de/maibornwolff/codecharta/visualization/app
|- axample (0 rloc)(0%)
|- **core** (1801 rloc)(23%)
|- **e2e** (28 rloc)(0%)
|- **ui** (5902 rloc)(76%)

That way I can immediately see that no code is inside axample and only a tiny amount in e2e.

**Comment by alschmut** [comment]
Do you think about the sizeMetric the user chooses from all the available metrics or about the kilobytes size of a folder?

**Comment by Richargh** [comment]
I mean the sizeMetric. Though we should think about adding the actual mb as a new metric :)

**Comment by Richargh** [comment]
And another one. CodeCharta should also display how big that subfolder is compared to other subfolders:

de/maibornwolff/codecharta/visualization/app
|- core (1801)(23%)
|- e2e (28)(0%)
|- ui (5902)(76%)

**Comment by alschmut** [comment]
I just checked the first implementation of this issue and I am not convinced to use the `rloc` metric here. We provide a generic application that should not depend on a specific metric, which might be there or not. While `rloc` is a close approximation on file size, I would rather rely on our unary metric. It always exists, as we add it during the loading process.
- A folder's unary metric contains the number of files (leafs). It does not count subfolders.
- A file's unary metric is always 1

---

As part of this issue, I would like to suggest to change the listing order to first show the folders and afterwards the files (inside its group, ordered by name like at the moment)

**Comment by alexhunziker** [comment]
I agree with @alschmut that we should not rely on rloc here, especially since it will not always exist. (The SCMLogParser for example does not generate rloc). Therefore if we are hard-coding a metric, it should be unary, since it is the only one that will always exist.

...Or we take the areaMetric/sizeMetric for the calculation as suggested originally by @Richargh

**Comment by JaiJoPa** [comment]
I agree with you @alschmut  and @alexhunziker , you're totally right! But I don't know either, if we should take the areaMetric/sizeMetric or just simply the unary metric. I think it depends on whats supposed to be the focus for the user. If it should let the user know how many files a folder contains, then totally unary. If we take sizeMetric, the user would have the choice, what number he wants to see in the the Treeview. 
I personally prefer the size Metric, because the user would have the possibility to chose unary, if he wants to see how many files a folder has or a different one but then, the sizeMetric would be responsible for not only the building size but also for the number which is shown in the treeview. I don't know thats so good, because maybe the user wants a different metric for the building size, but wants to see a different metric for the treeview filesize... 
The other question I have is, should the size of the files in Treeview change if the user changes the sizeMetric or should it just take the first chosen Metric and stick to it even when the sizeMetric changes?

**Comment by alschmut** [comment]
- Truely, using the areaMetric is an option, but how do you want to show that the numbers shown in the tree view then, come from the areaMetric? I think using the areaMetric or any other from the metricChooser is not useful:
- I prefer to easily use the `unary` metric and somehow mark the number as to be the number of subfiles!
- creating an extra chooser inside the tree view is another option, although I think this is definitely overkill and will not be enhance the user experience
- We should mostly keep in mind that the tree view already shows quite a lot of information:
  - number of searched files
  - number of excluded files
  - number hidden files
  - folder/file icon
  - visibility eye (potentially crossed)
  - green text color for searched nodes
  - option to right click the node
  and we should keep it as simple as possible for the user to understand how to use the tree view.

**Comment by Quicano** [comment]
Are there any more requests or possible improvements for this issue?

**Comment by alschmut** [comment]
@Quicano sorry I forgot to add a gif/screenshot of my changes. If you are happy with the design changes I made, you can create a PR. if not, feel free to comment you ideas or update the code

**Comment by Quicano** [comment]
@alschmut I like both solutions. 
stylistically yours is much better, even though I fear that, the deeper you go within the tree the more the 'number-of-files' funcion will go unnoticed, because it might be hidden in the far right corner of the treeview-window. 
Give this slight disadvantage I still think, that both solutions are valid and am happy with either one of them :)
