### ISSUE TITLE
Create a technical Dataflow that documents what happens when a new map is loaded into Codecharta

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#449]
Depends on #178

Use [Drawio](https://www.draw.io/). Guided by [this tutorial](https://github.com/jgraph/drawio/wiki/Embed-Diagrams) it should be possible to embed editable drawio diagrams in the documentation. 

![Database Schema](https://raw.githubusercontent.com/MaibornWolff/codecharta/master/gh-pages/images/Test.png)

[Edit here](https://www.draw.io/?title=Test.png&url=https%3A%2F%2Fraw.githubusercontent.com%2FMaibornWolff%2Fcodecharta%2Fmaster%2Fgh-pages%2Fimages%2FTest.png%3Ft%3D0).

**Comment by NearW** [comment]
![NewFileEventChart.png](https://images.zenhubusercontent.com/5cd16d629795a865159e710f/c2894a46-80db-4c97-8a60-869b8c1932eb)

Is this understandable?

**Comment by alschmut** [comment]
@NearW for me yes. Do you wanna add the entry points codecharta component and filechooser component on the top?

Also I think a separate graph with the redux cycle (circle) were nice as well, like:
- `abc.component.html` change UI property
- `abc.component.ts` dispatch redux action
- `store.service.ts` 
  - call individual reducer to set new property
  - send STORE_CHANGED event
- `property.service.ts` receive STORE_CHANGED event and send PROPERTY_CHANGED Event 
- `abc.conponent.ts` 
  - receive PROPERTY_CHANGED in `onPropertyChanged` method
  - set property into `_viewModel` object
- `abc.conponent.html` shoe new property value in UI

**Comment by NearW** [comment]
I thought it wouldn't be necessary to add a component on top, since the important stuff is service related in my opinion.

Yes, I think a data flow chart for component<->storeService interaction is a good idea, but that's not the scope of this issue. 

For me it would be great to get some feedback from @RomanenkoVladimir and someone unrelated to the code, such as @fatihi or @BridgeAR 

I used some specific terms, like "decorateMap" which is a method we use to sum the attributes from the leafs to the folders, which is not explained in the graph. I don't know if I should explain these things or leave them for the developer to look up in the code.
