### ISSUE TITLE
Visualization can export 3D printer files

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#475]
In addition to the regular cc.json export, we could also provide a 3d printer export. Then people could print their software and watch it grow, year after year. 

![Printer-Export.drawio.png](https://images.zenhubusercontent.com/5cd16a929795a865159e70ff/c0712b35-65e1-4ab3-8f37-9b1d2d60f4b5)

## Open Questions:
What should we do with the floor labels?
How should we prevent floating buildings/floors?
What should we do for tiny buildings?

**Comment by BridgeAR** [comment]
While it's a nice idea, I am not convinced we should implement something like that. Do you see an actual need for anyone to print code maps as a 3D model? It's probably not something many would need but mainly something to play around with?

**Comment by Richargh** [comment]
We had this feature on a branch at one point. @mrpatpat knows more. As far as I know it didn't take long to implement. A day maybe?

It's a vanity/gimmick for sure. I love the idea to be able to print the software. You could print it year after year and watch it change. After an audit you could give this as a final present (probably with modified colors). I did consider putting it in CC if the implementation cost was acceptable but then edges took priority and I forgot... :|

**Comment by mrpatpat** [comment]
As far as I remember we used a already implemented solution. I think it was based on the [STL-Exporter included in Three.js ](https://github.com/mrdoob/three.js/blob/master/examples/js/exporters/STLExporter.js). A usable example for a test print is located [here](https://threejs.org/examples/misc_exporter_stl.html)
It takes a scene as input and outputs a STL file which can be printed. 
I do not think integrating it is a complex task but there may be some needed work in order to make the codecharta scene itself ready for printing (e.g excluding hard to print structures like arrows or labels). 
I hope this helps. And yes it is a gimmick but it always sparked joy when we talked with people about it.

**Comment by BridgeAR** [comment]
The initial description for the feature request is to add it to the export feature. Let's discuss where to put the download button as the current one is actually planned for removal.

**Comment by IhsenBouallegue** [comment]
@BridgeAR I like doing it that way.
Well, it also means that we really are pushing this feature because it will be immediately visible. But I find this a good thing. As people will love it and share their 3D-printed maps with others and even the whole company. Good marketing for us.
We can have instead of the download button a 3D icon, and it converts the map into an STL file. The trickiest part is exporting it in a way that can be 3D printable (eliminating small buildings while still keeping the general look of the map)




> 
> 
> The initial description for the feature request is to add it to the export feature. Let's discuss where to put the download button as the current one is actually planned for removal.

**Comment by BridgeAR** [comment]
I would like to split the work into two parts. First of all implement the functionality that allows 3d printing. Triggering a download may be pretty much anything internal during that time. As soon as the functionality itself is fully implemented, let's focus upon where and how to implement the download functionality.

About the map size problem: we are able to provide a fixed maximum map size in e.g., `cm`. We now define the size of a pixel in `mm` and are now able to figure out the actual maximum that we are able to use. With that knowledge, the map itself is going to be rendered accordingly and very tiny buildings would not be rendered anymore (buildings below 1px size). In a later step we might allow the users to define their maximum value.

**Comment by IhsenBouallegue** [comment]
Should the ability to process the very small buildings be implemented in the first part or the second?
