### ISSUE TITLE
Fix SourceMonitor Script and document how to use it

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#562]
# Feature request

We supply a command-line script for SourceMonitor. This script is currently broken and unusable. Please fix the script and amend the SourceMonitor-UI documentation with a command-line example.

**Comment by Richargh** [comment]
@NearW isn't this issue done already? We have the following how-to for SourceMonitor: https://maibornwolff.github.io/codecharta/how-to/generate_with_sourcemonitor/

**Comment by BridgeAR** [comment]
Let's check if it's still an issue or not. If it is, please comment accordingly, otherwise close the issue with a comment.

**Comment by IhsenBouallegue** [comment]
Here are my findings
- The script works, but the command is not exactly as described in the how-to guide
- `./ccsh sourcemonitorimport PATH_TO_CSV_FILE -o C:/test.cc.json -nc` is what worked for me
  - This works in MINGW64, cmd and powershell give me the following error 
  `Der Befehl ""sh"" ist entweder falsch geschrieben oder konnte nicht gefunden werden.`
  - Executing `ccsh` works if I launch MINGW64 without admin privileges. With them, I have to navigate to where script is and do `./ccsh`
  - The `-p` flag doesn't work, it seems like it was removed. 
  - When executing the command with `-o C:/test`, the script will create a .gz file. This file can't be imported in CC because the file inside is missing the .cc.json extension.
  - A workaround is using the `-nc` flag (no compress) and specifying the extension manually by writing `C:/test.cc.json` for example.
- Note that Java is needed: I just installed the JDK 17, and it worked.
- Some of the problems are related to my environment, so I was not sure what problems were script related. I tried to mention everything that seemed relevant.

Here is the generated cc.json from the `analysis/import/CSVImporter/src/test/resources/sourcemonitor.csv` test file
![grafik](https://user-images.githubusercontent.com/48621967/142194825-ba78488f-588d-479d-910f-732f6fa1b175.png)
Everything seems to work also in visualisation
![grafik](https://user-images.githubusercontent.com/48621967/142194646-d3ac0d62-29ab-4802-aa86-1ca177385259.png)

**Comment by BridgeAR** [comment]
The output should have an extension by default. That way the compressed file would work again.
Besides that, let's update the documentation.

**Comment by IhsenBouallegue** [comment]
```
    @Test
    fun `should create json uncompressed file`() {
        main(arrayOf("src/test/resources/sourcemonitor.csv", "-nc",
                        "-o=src/test/resources/sourcemonitor.cc.json"))
        val file = File("src/test/resources/sourcemonitor.cc.json")
        file.deleteOnExit()

        assertTrue(file.exists())
    }
```
The tests show that the extension file should be specified, should we still change the Importer or just specify that in the documentation? 
Personally, I don't see any reason to change it. It works fine, we just need to know how to format the command correctly

**Comment by IhsenBouallegue** [comment]
The requested change of automatically adding the .cc.json file extension is way beyond the scope of this issue. For consistency, it needs to be done to all importers, and it is not an obvious solution. So here is what I did.
I fixed the documentation in this [PR](https://github.com/MaibornWolff/codecharta/pull/2521)
And let's move the discussion of the feature to this [new Issue](https://github.com/MaibornWolff/codecharta/issues/2522)
