### ISSUE TITLE
Security issue: shelljs

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#600]
# Bug and Security

## Problem

Our goal is not to prevent malicious attacks but prevent user problems from normal folder naming. Please make sure the user can have spaces and $ in folder names.

There are different shells that use different escape symbols. I would like to support Windows Terminal, Powershell and (git) bash.

## Notes

Escape symbols
- *nix uses \
- Windows Terminal uses ^

This almost works for *nix but not for Windows paths because the escape symbols are different:
```js
let escapedDirname = __dirname.replace(/(["$])/g, "\\$1");
console.log(__dirname);
console.log(escapedDirname);

let cmd = `npm run --prefix "${escapedDirname}" start`;
console.log(cmd);
require("shelljs").exec(cmd);```

**Comment by NearW** [comment]
https://www.npmjs.com/package/shelljs

The latest version is 0.8.3

Should we get rid of it entirely or wait for a fix?

**Comment by Richargh** [comment]
> The latest version is 0.8.3

That explains why Dependabot does not have a PR while Github informs us of the security issue. 

Can we get rid of it entirely? Then please do that.

**Comment by Richargh** [comment]
Also, we reached issue #600 💃

**Comment by NearW** [comment]
We use shelljs so that when you run install codecharta with `npm i -g codecharta-visualization`, you can simply run it with `codecharta-visualization` no matter what OS you're on.

`require("shelljs").exec(`npm run --prefix ${__dirname} start`)` 

We could try to implement a switch and make it work.

**Comment by Richargh** [comment]
Hmm. It's a great convenience function so I am hesistant to remove shelljs. Can we replace it with a different library? Otherwise I'd suggest we wait a couple of weeks for a fixed version.

**Comment by NearW** [comment]
https://github.com/shelljs/shelljs/issues/945#issuecomment-505094896

I'm not sure, if shelljs will provide an update that will sanitize your input.
```
shell.exec(`npm run --prefix ${__dirname} start`)
```

In our scenario we could get injected by the __dirname parameter to contain executable commands, but is this even possible?

**Comment by nfischer** [comment]
Hi, ShellJS maintainer here. Chiming in with a couple thoughts.

> I'm not sure, if shelljs will provide an update that will sanitize your input.

We're not going to sanitize your input for this API. This is an explicit requirement for using `shell.exec()`. We have [recommendations](https://github.com/shelljs/shelljs/wiki/Security-guidelines) to help you accomplish this.

> In our scenario we could get injected by the __dirname parameter to contain executable commands, but is this even possible?

I recommend you err on the side of caution. What if someone installs your project into a folder named `/path/to/malicious folder name; rm -rf*/subdir/` (all of which are legal unix filename characters)? Even if you think this is a non-issue because the attacker already has control over the system, the power to `mkdir` shouldn't be the power to execute arbitrary code. At the very least, you have a bug if you're installed in a folder with a space in the name, which is a totally reasonable folder name.

**Comment by Richargh** [comment]
Hi @nfischer. Thanks for replying on our issue. You bring up some excellent points concerning `__dirname` which we did not consider. I did not think about the *space in foldername* issue. We'll sanitize our input.

**Comment by fatihi** [comment]
We just updated the description and changed the goal.
