### ISSUE TITLE
Scmlogparser should explain if our file uses the wrong encoding

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#614]
# Bug

## Expected Behavior

Parsing a file of the wrong encoding should show a helpful message. I have added information to the wiki for this case but the current commandline error message only creates confusion.

## Actual Behavior

On windows machines generating a log file sometimes leads to a file that is encoded with non-UTF8. The scmlogparser then throws an exception `java.lang.IllegalArgumentException: no commit present or parallel stream of log lines, which is not supported` which is rather unhelpful.

## Steps to Reproduce the Problem

  1. Be on windows or change the file encoding to non-utf8 after generating the log file
  2. `git log --numstat --raw --topo-order > my.log`
  3. `ccsh scmlogparser my.log --input-format GIT_LOG_NUMSTAT_RAW -o my.cc.json`

## Specifications

  - Version: all of them, testet with 1.28 and 1.26
  - Platform: Windows, maybe some Mac or Linux versions

**Comment by Richargh** [comment]
The second option is ok in my opinion. `IllegalArgumentException` probably mostly happens for the wrong encoding. Please check if you can't figure out the file encoding beforehand. On the command line I can check and change the encoding with the methods described in our [wiki](https://github.com/MaibornWolff/codecharta/wiki/Using-Sonarqube-and-the-Log-from-Git-or-Svn-to-visualize-Codecharta's-own-Code#ensuring-the-encoding) so it should be possible to detect the encoding in Kotlin and adapt it in our parser.

**Comment by alexhunziker** [comment]
I am having some Gradle issues here...

In order to guess the Encoding of the input file i tried to use the TikaEncodingDetector from Apaches any23. However on building the project (disTar) gradle informed me that we are exceeding the number of documents it can pack into the archive and that i should use zip64 instead. So i researched how to do that, (since gradle did not tell me where to specify it). Anyways, i managed to do so, and Gradle did no longer complain about the number of files... but at the same time the ccsh is not executable anymore, I get this issue: 

```
$ ./ccsh
Fehler: Hauptklasse de.maibornwolff.codecharta.tools.ccsh.Ccsh konnte nicht gefunden oder geladen werden
```
Do you have any experience with this / idea on how to overcome the issue?
