### ISSUE TITLE
Performance while using sliders

### ISSUE THREAD

**Issue by mrpatpat** [MaibornWolff/codecharta#63]
using sliders triggers full map rebuild -> performance issues -> crash

**Comment by alschmut** [comment]
We could do less map rebuilds by adding a timeout/debounce (given in milliseconds) to the slider. That's pretty easy, but it interrupts the current fluent map changes for smaller maps.

`<input ... ng-model-options="{ debounce: 30 }" ...>`

**Comment by mrpatpat** [comment]
I also thought about debouncing but didn't know it can be implemented in such a nice way. What do you think about making the debounce time relative to the node count ? This would increase debounce in bigger maps and decrease it in smaller ones. The interactivity would change according to the map size.

**Comment by alschmut** [comment]
Yes, thats actually a good idea. Where or how can I find the node count?

**Comment by thorsten** [comment]
The Chrome dev tools can show the node numbers in the performance tab

**Comment by mrpatpat** [comment]
You can also inject the settingsService into your component and use the settings.map attribute (currently rendered map) like this: 
` let nodeCount = d3.hierarchy<CodeMapNode>(map.root).descendants().length;`
Also you need to be careful with ng-model-options="". In most cases CC does not use angular two way binding via model to actually set/read variables. ng-model is often used as a view-model and the actual set/read happens by explicitly calling or subscribing to a service (e.g. [color settings component](https://github.com/MaibornWolff/codecharta/blob/frontend_refactoring/visualization/app/codeCharta/ui/colorSettingsPanel/colorSettingsPanel.component.ts) ). 
I would also suggest that you develop the feature off the [frontend_refactoring](https://github.com/MaibornWolff/codecharta/pull/106) branch. It already contains important ui changes which could influence your code.

**Comment by FernandoES** [comment]
Another solution is a function that only calls applySettings when after some time it wasn't
 called again. In the branch performance ( I considered that a new branch is a better idea in order to roll back the suggestion if not accepted ) . Now every time that SettingsService.applySettings was called now applySettingsSlow is called (line 275), only if after 0,5s this function wasn't
 called again it calls applySettings.
The point of this is that in works as spected for slider, but also enhances the loading of the files, that previously were loaded four times on every loading. Loading of a big project file that previously took 4:37 mins now takes 0:37 (mean of three trials).
Check file: visualization/app/codeCharta/core/settings/settings.service.ts

**Comment by alschmut** [comment]
But now it doesn't apply the correct scenario and doesn't autoFit the camera angle

**Comment by FernandoES** [comment]
Thanks for the info, bug solved. 
The reason of the bug was that the method could be called with or without an argument, when it was called without argument the values of the system were used, so it was no problem to wait for the next calling to apply them, but when it was called with arguments waiting for the next calling produced the lost of those arguments. Now the calling waits only when done without arguments.
