### ISSUE TITLE
Move the file path and detail panel to the top

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#640]
# Feature request

CodeCharta currently shows the file path and the detail panel in the bottom left corner, when hovering. 

## Description

Please move it to the top left, so it's close to the metrics. Let's move it to the right if the search panel is open, so it's not visually blocked by the panel. The metric ribbon can overlay it.

**Comment by alexhunziker** [comment]
![grafik](https://user-images.githubusercontent.com/20796577/62054601-320b3580-b21a-11e9-88ca-dba102ca6d7b.png)

how about moving the view cube down at the same time? (I have the impression that otherwise it might get too busy on the top right) However in this case it is impossible to open the detail panel and the legend panel at the same time; is this acceptable?

**Comment by alschmut** [comment]
Regarding opening the detailPanel, I actually think it makes sense to implement #527 right away. #527 should make the detailPanel less distracting, when its opened and makes the above question @alexhunziker mentioned obsolete.

**Comment by alexhunziker** [comment]
hmm as far as i see #527 only specifies how the new detail panel should look like, and leaves open where to put the path indicator. 

However, in light of the upcomming #527, i suggest moving the components as proposed in the screenshot, as the overlapping of the legend panel is in this case only a temporary issue anyways.
