### ISSUE TITLE
New Importer: IndentationLevelImporter

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#660]
# Feature request

## Description

Create an importer that counts the indentation level of each line and generates an cc.json output with attributes like this:
```
{
    "il1+" : 1,
    "il2+" : 3
}
```
where il1 is the number of lines in the file with `indentation level 1 or higher`.

The `indentation level` is calculated by
```
(positionOfTheFirstCharacterInLine / tabWidth) + (positionOfTheFirstCharacterInLine % tabWidth == 0 ? 0 : 1)
```

The `tabWidth` needs to be estimated before.

The importer should be executable with:
`ccsh indentationlevelimporter FOLDER/FILE -p PROJECT_NAME -o OUPUT.CC.JSON`

**Comment by alschmut** [comment]
Isn't this Issue the same as #659? I guess the output is supposed to be a `cc.json`-schema and your specified outputs the node-attributes object, correct?
```json
"attributes": {
    "il1+" : 1,
    "il2+" : 3
}
```
Is `il` a common abbreviation for indentation level? What about the following metric suggestions, with more descriptive names?
- `max_indentation_level`
- `avg_indentation_level`

**Comment by NearW** [comment]
This importer will also create a cc.json. It can be merged with our results from the SourceCodeParser or SonarImport or whatever you desire.

@Richargh requested the number of lines with a certain indentation level. That's why we decided to create this metric.

**Comment by Richargh** [comment]
This is quite different from #659. #659 is only for Java code and it counts nesting, f.ex. an if, inside an if, inside an if. This issue counts the nesting level, how much white space is at the beginning of the line. In well-formated code the results should be quite similar and somewhat similar to McCabe Complexity. In badly formatted code, ... not :) 

So why should we do this? Because it works for all plain text files. Java, Xml, C# etc. We don't have to change it for new languages. Together with the tokei-importer we can support, out of the box, all possible programming languages.

**Comment by Richargh** [comment]
>  max_indentation_level
> avg_indentation_level

@NearW these are useful but not what we are looking for. You want to see how many buildings have a high indendation level. By selecting il4+ or il5+ the only buildings that are visible are *bad* buildings. Max and average indendation level provide a different and also useful view.

**Comment by alschmut** [comment]
Thanks @Richargh! Having metrics for all files out of the box is pretty cool 👍 still, I would rename the metrics to `indentation_level_1+` etc. ;)

**Comment by alexhunziker** [comment]
I have implemented this one yesterday. See branch https://github.com/MaibornWolff/codecharta/tree/feature/660/indentation-level-parser

While i was implementing it, I felt linke a significant portion of the logic is identical to the sourceCodeParser. Since these two do different things (one provides a wrapper for executing Sonar Plugins, while this one allows to line by line analyzing files ourselves) i think having the m in distinct importers makes sense here. However I thought that we may want to generalize this importer, so that it can be extended to calculate other metrics than the indentaion levels as well.
Why do I suggest this? Because any time we implement something similar (as for example #281 ) we basically have to re-write large portions of this importer again. Here we have the opportunity to make the architecture more flexible to allow introducing additional metrics in the future. (This would of course cause the importer not to be called indentationLevelImporter or similar)

What do you think about this? Should I adapt the architecture so that it can be extended in the future? (If this is not desired the user-story as specified above is currently implemented)

**Comment by alschmut** [comment]
I am personally in favour of generalising the importer. It's gonna be like with the SCMLogParser for parsing the log file. We can simply check additional metrics without writing the whole parser again.

Only question is: How do we name the importer, as we already have the "SourceCodeParser", which were an appropriate name for this one as well?

**Comment by Richargh** [comment]
One question, does this generalization conflict with [ADR 6: Filters share nothing ](https://maibornwolff.github.io/codecharta/adr/ADR_6_filters_share_nothing/)?

**Comment by alexhunziker** [comment]
> One question, does this generalization conflict with ADR 6: Filters share nothing ?

I would suggest implementing it like the SCMLogParser, in other words all metrics are calculated by the same filter and thus the share nothing principle will not be violated. The potential drawback is, that there may be (too) many command line arguments (... that is if we make the metrics customizable. if we just hard-code the parameters as done in the SCMLogParser the interface stays clean. It is a trade-off i guess)

> How do we name the importer, as we already have the "SourceCodeParser", which were an appropriate name for this one as well?

Good question, I asked myself the same and have found no good answer yet.

**Comment by alschmut** [comment]
I see it like the decision for creating the SourceCodeParser: Its purpose is to combine the functionality to parse different languages using sonar plugins. According to the statement that importers (and/or filters) do not share anything, we would have had to create multiple importers, like the JavaSourceCodeParser etc.

So, if we want to create our own custom metrics, we would have to rebuild the base for parsing each file line by line for every added metric inside an extra importer. Why not combine those in a sensual architecture, where we can create new metrics without creating a whole new importer?

**Comment by Richargh** [comment]
Wait, wait, wait. ADR-6 is only about dependencies between projects. You can abstract whatever you want inside an importer, exporter whatever. They are not allowed to share anything between them however. 

The SourceCodeParser for example could parse Java, JavaScript etc., no problem at all. You just cannot share the logic with another parser.

**Comment by alschmut** [comment]
yea, exactly @Richargh 😃 they don't share any logic. All custom metrics will be handled inside one importer.

**Comment by alschmut** [comment]
@alexhunziker I am not into the code yet, but did think about the option of implementing these new custom metrics into the SourceCodeParser? Would that make sense or is the architecture rather very different?

**Comment by Richargh** [comment]
Why put it into the SourceCodeParser? @alexhunziker what metrics does the IndendationLevelParser create that the SourceCodeParser also creates? What is actually the same? The ILParser does not have any Sonar and doesn't it only create indendation level, while the SCParser creates all Sonar metrics + custom nesting level?

**Comment by alschmut** [comment]
@Richargh I just remembered that we named the SourceCodeParser, because it analyses source code from projects we have on our machine. That is kind of the same with any new importer (for new metrics), which parses projects locally.

I don't think the SCParser and the ILParser share any metrics though.

**Comment by alexhunziker** [comment]
> @alexhunziker I am not into the code yet, but did think about the option of implementing these new custom metrics into the SourceCodeParser? Would that make sense or is the architecture rather very different?

The architectures are indeed very similar, and an integration technically possible. However I don't know if this is conceptually desirable, since they do kinda different things; the (sonar) sourceCodeParser gets base metrics for certain languages (currently java only) while this thing here provides some special metrics for any file scanned (that may or may not be meaningful). I don't know if the use case for this and the (sonar) sourceCodeParser are similar enough to fuse them together. Also the CLI options of a fused importer may get confusing.

> Why put it into the SourceCodeParser? @alexhunziker what metrics does the IndendationLevelParser create that the SourceCodeParser also creates? What is actually the same? The ILParser does not have any Sonar and doesn't it only create indendation level, while the SCParser creates all Sonar metrics + custom nesting level?

The metrics we are obtaining with the new Parser cannot be obtained by Sonar Directly, the only thing it does is computing the maximum nesting level (we created a custom metric for that). It would be possible to generate a custom metric for the sonar plugins that provides the same information as the indentation level parser does, however they would be only applicable to certain programming languages (i.e. Java only at this point)
