### ISSUE TITLE
Make the purpose of hide/exclude clear

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#691]
# Feature request

I am pretty sure that the purpose of hide an exclude is not clear to our users. Let's change that by adding some descriptive text to the hide and exclude dropdowns. I propose three things as seen below.

**Intended** as a quick-fix: if this is not simple to do within **a couple of hours** then please 1) don't do it, 2) comment why it's difficult (tech issues, test issues, unclear goals, etc.) 3) let's figure out together if we should do it.

## Description

1) I think the hide and exclude Dropdowns should start with a simple Headline (please comment or change the wording for clarity):

--------

### Hidden (or should we change this to "Flattened"?)
Hidden buildings are flattened and are included in folder metrics.

### Excluded
Excluded buildings are not shown in the map, but still stored in the file and not included in folder metrics.

--------

2) Below that is an underlined description "add with search or node context menu"
I think the underline makes it look like this is a search field, so we should probably remove that line. Also I think this message should only be displayed, when the list is empty.

3) When an item is exclude or hidden it has the exclude or hide symbol on the left and trash icon on the right: 
![Screenshot 2019-08-16 at 14.27.36.png](https://images.zenhubusercontent.com/5cd16a929795a865159e70ff/7e59c2db-db1a-4138-9bde-2f018bdb1205)
We don't need the exclude or hide symbols any more, because we split the backlist into hide and exclude. The trash symbol is confusing because our users are afraid, that clicking it might lead to data loss. Also the trash symbol is on the right side, which means we need to scroll all the way to the right to reshow an excluded or hidden item with a long name.

My idea is to remove trash, exclude and hide symbols. The latter two are not needed. The effect of the trash first one is to **reshow** whatever was excluded/hidden. So instead we'll place left of the hidden/excluded text an eye symbol to indicate we can show the item again.

**Comment by Richargh** [comment]
@alschmut @NearW @alexhunziker and @JaiJoPa can you please comment on the ideas and text in this issue?

**Comment by alschmut** [comment]
I like:
- The headline and I am convinced to change hidden to flattened 👍 
- removing the grey line below the description
- removing the hide/exclude button

I am not quite sure about the eye though, not because of the icon and its meaning you described, but because how we treat the node. Technical question: Do we then add another visible-tag to the object like this? And is the visible tag exported when downloading the map?
```javascript
export interface BlacklistItem {
    path: string
    type: BlacklistType
    visible: boolean
}
```

**Comment by Richargh** [comment]
> I am not quite sure about the eye though, not because of the icon and its meaning you described, but because how we treat the node. Technical question: Do we then add another visible-tag to the object like this? And is the visible tag exported when downloading the map?

This issue is not intended to change the behavior of CC in any way. So whatever the visible-tag is currently and whatever is exported stays the same. It's just a cosmetic change of wording. No cc.json needs to be modified either. Does that remove the confusion?

**Comment by NearW** [comment]
Let's use [this icon](https://fontawesome.com/icons/minus-circle?style=solid) instead of the trashcan. If I remember correctly, users thought that they might delete something when pressing that button.

**Comment by alschmut** [comment]
Okey, okey, so when I press the eye, the list entry will be removed, just like the trash worked before with a different icon?

**Comment by NearW** [comment]
Since the eye-icon is used as an indicator, that something is hidden/flattened, we should use another icon to remove blacklist entries in general.

I thought about [this](https://fontawesome.com/icons/minus-circle?style=solid)

**Comment by Richargh** [comment]
> Okey, okey, so when I press the eye, the list entry will be removed, just like the trash worked before with a different icon?

Yes, it's a purely cosmetic choice so users are no longer afraid of the trash can :) That's also why I am skeptical about the `-` that @NearW suggested. Doesn't that also seem destructive?

**Comment by NearW** [comment]
We don't have many options left. [X](https://fontawesome.com/v4.7.0/icon/times) or [-](https://fontawesome.com/v4.7.0/icon/minus)

I personally don't think about a permanent removal or destruction, when I click a minus-button.

**Comment by alschmut** [comment]
That's kind of a hard decision. In every application a trash can or similar is used to indicate deleting a list item. Do we really have some actual feedback, that people are afraid of clicking the trash can icon?

How about some other idea to go even further with renaming: What if we keep the same functionality, but...
- rename `Hide` to `Flatten` and
- rename `Exclude` to `Hide`
Hiding nodes sounds less extreme and when having a headline like **Hidden nodes:**, people might be less afraid to delete a list item?

It's just an idea to think about, and I am not 100% convinced either, as `exclude` still sounds more like "actually not even considering a node".

**Comment by alexhunziker** [comment]
So i like the idea or renaming hide to flatten (and I already did a branch with it), however there are some open issues:

1. We already have a flatten option in CodeCharta, in the settings menu. If this option is active buildings not matching the current search pattern become light grey and almost flat. So If the blacklist hide becomes flatten - flatten has to be renamed too...
2. The icons. The eye icon is good for hide, but not for flatten... does anybody have an idea for a new icon "flatten"? (If we find an appropriate icon we can use the eye icon for the other category and rename it from exclude to hide. However if we are keeping the icons as they are i would not rename them since hide is really associated with the eye)

**Comment by alschmut** [comment]
1. we could rename the `flattened` attribute in the settings to `hideFlatBuildings`
1. I can not think about any other than the `Window minimize` fa-icon.. It's quite difficult to search for a "flat icon" as well.

If we would rename `hide` to `flatten`, should we then also show the buildings flattened, if the settings option `hideFlatBuildings ` is not set to true, because at the moment we hide hidden buildings (obviously).

**Comment by alexhunziker** [comment]
Ok, i suggest we leave the icons as they are & wait if users find them confusing...

> If we would rename hide to flatten, should we then also show the buildings flattened, if the settings option hideFlatBuildings is not set to true, because at the moment we hide hidden buildings (obviously).

That sounds reasonable, we should do that
