### ISSUE TITLE
Mark color-section as unimportant in delta mode

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#769]
# Feature request

## Description

This issue originated from an [696 issue comment](https://github.com/MaibornWolff/codecharta/issues/696#issuecomment-548821679)

In delta mode the chosen color-metric has no impact at all, as the map is coloured according to the difference of the height metric. So maybe we should show the color-metric section differently when delta is activated, ex. following options
- remove the section
- darken the section in light grey
- disable the metric-chooser select
- not show hovered-values for the color-metric

... or a combination of multiple options

**Comment by alschmut** [comment]
In my opinion, I would do at least the following:
- disable the metric-chooser select and
- not show hovered-values for the color-metric

**Comment by BridgeAR** [comment]
We should figure out how deactivating the the color metric plays nicely with choosing different colors. @Gaugi28 do you have any thoughts on this?

**Comment by Gaugi28** [comment]
After discussion with @BridgeAR:
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a user, I want color settings in the delta mode, so I can change the color. Further I don't want to see metrics which I cannot change in the delta mode like the color and edge metrics.

## Acceptance criteria
- In the delta mode the color and edge metric input fields are removed.
- Instead of the color metric there is a dropdown where the user can set the colors (see image). 
- The dropdown has the label "Color Settings".
- The user can pick the color as described [here](https://github.com/MaibornWolff/codecharta/issues/1533).

![ColorSettingsDeltaMode](https://user-images.githubusercontent.com/12883714/103989476-0a9af500-5190-11eb-8f9e-b2c26593f198.png)
![image](https://user-images.githubusercontent.com/12883714/103989694-61a0ca00-5190-11eb-9ca3-2adae5cee5ac.png)
