### ISSUE TITLE
CodeCharta Analysis Coverage is 0%

### ISSUE THREAD

**Issue by Richargh** [MaibornWolff/codecharta#787]
# Bug

## Expected Behavior

Coverage fulfills the quality profile we set ourselves.

## Actual Behavior

* Version 1.22.0 March 2019 had 48% coverage
* Version 1.23.0 April 2019 dropped to 12%, then to "up" to 14.1%
* Version 1.24.0 May 2019 went from 14.1% to 0%

**Comment by BridgeAR** [comment]
@RomanenkoVladimir had a look at this and the outcome is that it's indeed as low as reported. Writing tests should always be a high priority and to make sure the coverage is increasing we'll take the following steps:

1. We include tools such as codecov to verify that pull requests always increase the coverage. Lowering the coverage would prevent merging the PR and as such enforce writing more tests.
2. We start with an initial sprint focusing on writing tests for files with a coverage < 10%.
3. Anyone who is just remotely working on parts that are not yet covered should write a test for such code.

It'll then be an ongoing process to increase the coverage while not blocking development of other new features.

**Comment by RomanenkoVladimir** [comment]
We discussed the frontend sonar issues to also be a part of this, 
the frontend part should be fixed now

**Comment by NearW** [comment]
I am pretty sure that our coverage is not 0%. There are actually a lot of tests in the analysis.
The problem here must be an issue with our sonarcloud configuration.

Sonarcloud is not running tests. Sonarcloud is actually importing coverage results. We build these with travis and publish them on sonar afterwards. You have to specify where sonar finds these.

For Javascript/Typescript this must be specified in a sonar.properties file with `sonar.typescript.lcov.reportPaths=./dist/coverage/lcov.info`. 

For Kotlin this must be done here `sonar.coverage.jacoco.xmlReportPaths`. See https://sonarcloud.io/documentation/analysis/coverage/ for more information on that.

We need to generate coverage reports and specify the path to that in our build.gradle file.
