### ISSUE TITLE
Clean up UI

### ISSUE THREAD

**Issue by ukinimod** [MaibornWolff/codecharta#86]
There are some elements in the UI that I think are not needed. Probably these should be separate issues. For that. Anyway, I would like to discuss them with you:

1. Scaling is probably only needed for the height of the buildings. I can think of no use case with scaling the other axis separately and simultaneous scaling corresponds zooming, I think. Changing the name of y to height would improve understanding. I think choosing absolute values for scaling should not be necessary.

2. It would be great to have a different symbols for scenarios and metrics.

3. I would rather put the statistic functionality to experimental as I don't have a use case for it as of now (have you?).

4. Having the same icons in the legend and in the hover info would be great. There is also a misplaced "," in the legend.

5. It would be great if the legend wouldn't show the delta symbols when in "normal" mode.

6. The tree view shows some strange bar on the right side. Is there any meaning behind this?

**Comment by mrpatpat** [comment]
Hi @ukinimod !

thank you for the feedback. These points seem valid to me. i think the only discussion needed is about point 3.  

1. I absolutely agree. I removed the unnecessary sliders. 
2. I added a star as the symbol for the scenarios (Since this feature resembles something like "favourites")
3. I think we need to discuss this with @FernandoES since he implemented this feature by himself and knows the requirement rationale. 
4. and 5. This is a nice addition. Fixed.
6. This is a scrollbar. It actually it is not necessary anymore since the settingspanel itself is now scrollable. I removed it.
