### ISSUE TITLE
Excluding the last building on the map results in an error, reincluding the buildings makes them all the same size

### ISSUE THREAD

**Issue by RomanenkoVladimir** [MaibornWolff/codecharta#901]
# Bug
Console Error after last building is excluded, Error in Building Size and Color afterwards if buildings are included again
## Expected Behavior
When the user excludes the last building the map is empty, reincluded buildings look the same as before exclusion.
## Actual Behavior
When the user excludes the last building on the map a console error is thrown, reincluding buidlings afterwards results in all of them being color, due to the metric switching to unary
## Steps to Reproduce the Problem
  1. Exclude all buildings
  2.  The Web Application throws a TypeError: "reduce of empty array with no initial value"
  3. Reincluding buildings makes them all red, metric switches to unary

## Specifications
  - OS: Windows
  - Browser: Firefox, Chrome

**Comment by alschmut** [comment]
I don't want to defend this behaviour, its not ideal, but I wanna mention that this is strictly not a bug but by design. 
- The root node includes the metric (attributes) of its children. In this case the root node does only contain the fake metric `unary`, as it has no children. 
- And whenever the available metrics change, the selected metrics reset themselves to the first available metric, which in the case is `unary`

**Comment by RomanenkoVladimir** [comment]
Ah ok, I understood what led to the behaviour but still thought a user would expect a similar color scheme to the one before the exclusion. If this is a decision by design, I was wrong here.

However, the console error still remains.

Should I change the issue or close it?

**Comment by alschmut** [comment]
Yes you are right, we could think of another solution here. Not sure what you mean with color scheme though, as there is not other available metric nor more than one node ;) 

Nah, lets keep the issue as a bug (as it looks like one from a user perspective). But it requires more like a workaround than a fix.

**Comment by BridgeAR** [comment]
I had another look at this. There are actually different ways how a user might end up with no nodes at all.

If a user clicks on a building or folder that would end up in having no nodes left by excluding them, I would just open a popup warning that it's not possible to hide all nodes.

Another way to exclude all nodes is by e.g., searching for `*` and then to use that as an exclude pattern. I would open the same popup that notifies the user that this is not possible.

To do so, we could just check if the exclude operation would result in having no nodes left. If that's the case, open the mentioned notification and prevent the actual operation from succeeding (i.e., the exclude pattern from the search should not be added to the pattern list).

I changed the priority of this issue, since it's pretty easy to run into this and it ends up with very weird behavior afterwards.
