### ISSUE TITLE
Validate exported files with json schema

### ISSUE THREAD

**Issue by alschmut** [MaibornWolff/codecharta#946]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a user, I want exported files to be valid, so that I can import those into the application (where the imported file is validated) or use them with the `ccsh` without getting validation errors.

## Acceptance criteria
- Validate the `CCFile` object with `ajv` (see `fileValidator.ts`) before downloading (see `fileDownloader.ts`)
- Add useful unit tests to validate the object before downlaoding

## Development notes (optional Task Breakdown)
- [ ] 
- [ ] 
- [ ]

**Comment by BridgeAR** [comment]
An export should always be valid. If we export an invalid cc.json, there's a bug in our code. Instead of validating something in this step or having tests for such validation, we should make sure to have tests that verify that the data is correct so that no further validation is required.

This also conflicts with the plan to change the current export functionality in general. I am therefore going to close this issue.

Please reopen, if anyone thinks this should stay open.
